# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ccb17978adb9ba60c9dfe0dbd9dcfdfb9a4f16eeebede7b6edcd25625356f8912afc8463830a9f6d09d3fbba38253791c3ed722cc07a59e38ab9e38f5b4d0a70

test:
  secret_key_base: b91f2c46a00a9750a062d877bc49f6d474eec8438bfb7c9bc37f9ada61cbc55631834f8faee40790e5dc0562d2eb53a6eb3f55ab1e3bcf8587abed586bef6afb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
